export const LOGIN_USER_WITH_GOOGLE = 'LOGIN_USER_WITH_GOOGLE'
export const LOGIN_USER_WITH_GITHUB = 'LOGIN_USER_WITH_GITHUB'
export const LOGIN_USER_WITH_TWITTER = 'LOGIN_USER_WITH_TWITTER'
export const LOGIN_USER_WITH_FACEBOOK = 'LOGIN_USER_WITH_FACEBOOK'
export const LOGIN_USER_WITH_EMAIL = 'LOGIN_USER_WITH_EMAIL'

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'